services:
  chatlearn:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - API_KEY=${GROQ_API_KEY} # Variável de ambiente para chave da API
      - PYTHONPATH=/app    # Define o caminho do Python dentro do container
    networks:
      - chatlearn_network
    command: streamlit run app/ui.py

  test:
    build: .
    command: pytest --disable-warnings --maxfail=1
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app  # Adicionando /app ao PYTHONPATH também aqui
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - chatlearn_network


networks:
  chatlearn_network:
    driver: bridge
